# Generated by Django 4.0 on 2022-01-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='filename',
        ),
    ]
