# Generated by Django 4.0 on 2022-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContact', '0005_alter_predict_prediction_alter_predict_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='kine',
            field=models.CharField(default='kine', max_length=50),
        ),
    ]
