# Generated by Django 4.0 on 2022-04-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContact', '0006_file_kine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='kine',
        ),
        migrations.AddField(
            model_name='file',
            name='bool_predict',
            field=models.CharField(default='ok_predict', max_length=50),
        ),
    ]
